### ISSUE TITLE
[Roadmap] Temporal Roadmap for upcoming Godot 4.1 release.

### ISSUE THREAD

**Issue by MrBBBaiXue** [bakneko/godot-template#9]
- [ ] Multithreaded loading (has been fixed in godot master)
- [ ] Take a look at #7, which HiDPI support also relates to it.
- [ ] Pause / Resume menu support.
- [ ] Update README, changelog, wiki (images in .github folder)
- [ ] Github Actions support (Multiple pck export support.)

If you have any suggestions / bug feedbacks, feel free to comment in this issue!

**Comment by mrbbbaixue** [comment]
Godot 4.1 has released, will working on this repo.

**Comment by eerbin13** [comment]
> Godot 4.1 has released, will working on this repo.

That's reassuring. Continuing to use this template as a base then. :)

**Comment by mrbbbaixue** [comment]
> > Godot 4.1 has released, will working on this repo.
> 
> That's reassuring. Continuing to use this template as a base then. :)

Thanks, still looking for free time these days actually 😭
